export const GamePlatforms: string[] = [
    'Windows PC',
    'Linux',
    'Mac OS X',
    'Android',
    'iOS',
    'Web Browsers',
    'Magnavox Odyssey',
    'Fairchild Channel F',
    'Atari 2600',
    'Intellivision',
    'ColecoVision',
    'Atari 5200',
    'Magnavox Odyssey 2',
    'NES',
    'Master System',
    'Mega Drive',
    'Super Nintendo',
    'Sega CD',
    'Neo Geo',
    'Sega 32X',
    'Sega Saturn',
    'PlayStation',
    'Nintendo 64',
    'Dreamcast',
    'Xbox',
    'GameCube',
    'PlayStation 2',
    'Xbox 360',
    'Wii',
    'PlayStation 3',
    'Wii U',
    'Xbox One',
    'PlayStation 4',
    'Nintendo Switch',
    'Game Boy',
    'Game Boy Color',
    'Game Boy Advance',
    'Game Gear',
    'Lynx',
    'Neo Geo Pocket',
    'N-Gage',
    'Nintendo DS',
    'Nintendo DSi',
    'Nintendo 3DS',
    'New Nintendo 3DS',
    'PlayStation Portable',
    'PlayStation Vita',
    'Nvidia Shield'
];