export const GameGenres: string[] = [
    'Action',
    'Adventure',
    'RPG',
    'Platform',
    'Shooter',
    'Fighting',
    'Rhythm/Musical',
    'Simulation',
    'Strategy',
    'Racing/Sports',
    'Party',
    'Puzzle',
    'Card',
    'Board',
];
